ToDo/urls.py
from django.contrib import admin
from django.urls import path, include
import Users.views as userView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('register/', userView.register, name="register"),
    path('login/',userView.loginPage, name="login"),
    path('logout/',userView.logoutPage,name="logout")
]

Users/models.py
from django.db import models

# Create your models here.

Users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.forms import SelectDateWidget


class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)

    class Meta:
        model = User
        fields = ["first_name", "last_name", "username", "password1", "password2", "email"]

Users/views.py
from django.shortcuts import render, redirect
from . import forms
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout


# Create your views here.

def register(request):
    error = ""
    if request.method == "POST":
        form = forms.RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Your account created successfully!")
            return redirect("login")
        error = list(form.errors.items())
        for i in range(len(error)):
            error[i] = "".join(error[i][1])
    else:
        form = forms.RegistrationForm()
    if error != "":
        print("ERROR::::: " + str(error))
    return render(request, 'Users/register.html', {"errors": error})


def logoutPage(request):
    logout(request)
    return render(request, "Users/logout.html")


def loginPage(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("main_home")
        else:
            return render(request, "Users/login.html", {"error": "Username or password is incorrect"})
    else:
        return render(request, "Users/login.html")

Users/templates/Users/login.html
{% extends 'main/base.html' %}
{% block content %}
<h2 class="loginTitle">Sign in</h2>
{%if error%}
<div class="errorWrongAuthentication">
    <p>{{error}}</p>
</div>
{%endif%}
<div class="loginForm">
    <form method="POST">
        {% csrf_token %}
        <div class="formGroup">
            <label for="id_username">Username</label>
            <input type="text" name="username" maxlength="150" autofocus class="textInput form-control" required
                id="id_username">
        </div>

        <div class="formGroup">
            <label for="id_password1">Password</label>
            <input type="password" name="password" autocomplete="new-password" class="textInput form-control" required
                id="id_password1">
        </div>
        <div class="submitButton">
            <button type="submit" class="btn-signIn">Sign in</button>
        </div>
        <a href="{%url 'login' %}" class="forgottenPassword"><small>Forgotten password?</small></a>
        <div class="link-to-register">
            <small>* doesn't have any account?</small>
            <a href="{%url 'register' %}" class="link-to-register">&nbsp;&nbsp; Sign up</a>
        </div>
    </form>

</div>
{% endblock content%}

Users/templates/Users/logout.html
{% extends 'main/base.html' %}
{% block content %}
<div class="logut">
    <p>You are logt out now</p>
    <a href="{% url 'login' %}">log in</a>
</div>
{% endblock content%}

Users/templates/Users/register.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<h2 class="registerTitle">Create a new account</h2>
{% if errors %}
{% for error in errors %}
<h6 class="error">* {{error}}</h6>
{% endfor%}
{%endif%}
<div class="registerForm">
    <form method="POST">
        {% csrf_token %}
        <div class="formGroup2">
            <div>
                <label for="id_first_name">First name</label>
                <input type="text" name="first_name" maxlength="30" required id="id_first_name" class="textInput">
            </div>
            <div>
                <label for="id_last_name">Last name</label>
                <input type="text" name="last_name" maxlength="30" required id="id_last_name" class="textInput">
            </div>
        </div>
        <div class="formGroup">
            <label for="id_username">Username</label>
            <input type="text" name="username" maxlength="150" autofocus class="textInput" required id="id_username">
            <small class="text-muted">150 characters or fewer. Letters, digits and @/./+/-/_ only.</small>
        </div>

        <div class="formGroup">
            <label for="id_password1">Password</label>
            <input type="password" name="password1" autocomplete="new-password" class="textInput" required
                id="id_password1">
        </div>
        <small id="hint_id_password1" class="text-muted">
            <ul>
                <li>Your password can’t be too similar to your other personal information.</li>
                <li>Your password must contain at least 8 characters.</li>
                <li>Your password can’t be a commonly used password.</li>
                <li>Your password can’t be entirely numeric.</li>
            </ul>
        </small>
        <div class="formGroup">
            <label for="id_password2">Password confirmation</label>
            <input type="password" name="password2" autocomplete="new-password" class="textInput form-control" required
                id="id_password2" class="formInput">
        </div>
        <div class="formGroup">
            <label for="id_email">Email</label>
            <input type="email" name="email" maxlength="254" class="emailinput textInput" id="id_email">
        </div>
        <div class="submitButton">
            <button type="submit" class="btn-register">Create account</button>
        </div>
        <a href="{%url 'login' %}" class="link-to-register"><small>Already have account?</small></a>
    </form>
</div>

{% endblock content%}